---
- apt: name=git state=present

- name: Create rbenv user
  user: name={{ rbenv_user }} shell=/bin/bash

- name: Create rbenv directory
  file: >
    path={{ rbenv_root }}
    owner={{ rbenv_user }}
    group={{ rbenv_user }}
    mode=2755
    state=directory

- name: Install rbenv
  git: >
    repo=git://github.com/sstephenson/rbenv.git
    dest={{ rbenv_root }}
    accept_hostkey=True
  sudo: yes
  sudo_user: "{{ rbenv_user }}"

- name: Create shims directory
  file: >
    path={{ rbenv_root }}/shims
    owner={{ rbenv_user }}
    group={{ rbenv_user }}
    mode=2755
    state=directory

- name: Create versions directory
  file: >
    path={{ rbenv_root }}/versions
    owner={{ rbenv_user }}
    group={{ rbenv_user }}
    mode=2755
    state=directory

- name: Create plugins directory
  file: >
    path={{ rbenv_root }}/plugins
    owner={{ rbenv_user }}
    group={{ rbenv_user }}
    mode=2755
    state=directory

- name: Install /etc/profile.d/rbenv.sh
  template: >
    src=rbenv.sh.j2
    dest=/etc/profile.d/rbenv.sh
    mode=644
    owner=root
    group=root

- name: Install dependencies for ruby-build
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev

- name: Install ruby-build as rbenv plugin
  git: >
    repo=https://github.com/sstephenson/ruby-build.git
    dest={{ rbenv_root }}/plugins/ruby-build
    accept_hostkey=True
  sudo: yes
  sudo_user: "{{ rbenv_user }}"

- name: Check installed ruby versions
  sudo: yes
  shell: "sudo -iu {{rbenv_user}} rbenv versions --bare"
  register: rbenv_installed_ruby_versions
  changed_when: False

- name: Install ruby versions
  sudo: yes
  command: "sudo -iu {{rbenv_user}} rbenv install {{ item }}"
  with_items: rbenv_ruby_versions
  when: rbenv_installed_ruby_versions.stdout.find("{{ item }}") == -1

- name: Check default ruby version
  sudo: yes
  shell: "sudo -iu {{rbenv_user}} rbenv global"
  register: rbenv_installed_default_ruby_version
  changed_when: False

- name: Set default ruby version
  sudo: yes
  command: "sudo -iu {{rbenv_user}} rbenv global {{ rbenv_default_ruby_version }}"
  when: rbenv_installed_default_ruby_version.stdout.find("{{ rbenv_default_ruby_version }}") == -1

- name: Check installed bundler gem for ruby versions
  sudo: yes
  shell: "sudo -iu {{rbenv_user}} rbenv whence bundle"
  register: rbenv_installed_bundler_versions
  changed_when: False
  ignore_errors: True

- name: Install bundler gem for ruby versions
  sudo: yes
  command: "sudo -iu {{rbenv_user}} gem install bundler --no-ri --no-rdoc"
  with_items: rbenv_ruby_versions
  when: rbenv_installed_bundler_versions.stdout.find("{{ item }}") == -1
